#!/bin/bash

EXTENSION_BASE=/etc/jupyter

if [ -n "$1" ]; then
  JUPYTER_EXTENSION_ARCHIVE=$1
  JUPYTER_EXTENSION_NAME=`basename ${JUPYTER_EXTENSION_ARCHIVE%%.*}`
  mkdir ${EXTENSION_BASE}/${JUPYTER_EXTENSION_NAME}
  tar -xzf ${JUPYTER_EXTENSION_ARCHIVE} -C${EXTENSION_BASE}/${JUPYTER_EXTENSION_NAME}
  jupyter nbextension install ${EXTENSION_BASE}/${JUPYTER_EXTENSION_NAME}/ --user
  jupyter nbextension enable ${JUPYTER_EXTENSION_NAME}/main
fi 
