version: '2'
services:
  proxy:
    container_name: "${PROXY_SERVER_NAME}"
    image: "${PROXY_DOCKER_IMAGE}"
    network_mode: host
    volumes:
    - /certs/jupyter-server.crt:/etc/ssl/certs/server.crt:ro
    - /certs/jupyter-server.key:/etc/ssl/private/server.key:ro
    - /certs/rootCA.pem:/etc/ssl/certs/ca-bundle.crt:ro
    - /etc/cluster-site.conf:/etc/apache2/sites-enabled/site.conf
    - /auth_openidc.conf:/etc/apache2/mods-enabled/auth_openidc.conf
    restart: always
    environment:
      HTTPD_PORT: '80'
      SSL_HTTPD_PORT: '443'