version: '2'
services:
  rstudio:
    container_name: "${RSTUDIO_SERVER_NAME}"
    image: "${RSTUDIO_DOCKER_IMAGE}"
    network_mode: host
    restart: always
    environment:
      # needed to disable auth
      USER: "rstudio"
      GOOGLE_PROJECT: "${GOOGLE_PROJECT}"
      WORKSPACE_NAMESPACE: "${GOOGLE_PROJECT}"
      CLUSTER_NAME: "${CLUSTER_NAME}"
      OWNER_EMAIL: "${OWNER_EMAIL}"
    volumes:
      - rstudio-working:/home/rstudio
    env_file:
      - /etc/google_application_credentials.env

volumes:
  rstudio-working:
  
