swagger: '2.0'

info:
  title: Leonardo
  description: |
    Workbench notebooks service.
  version: "0.1"
  license:
    name: BSD
    url: http://opensource.org/licenses/BSD-3-Clause
  termsOfService: https://github.com/broadinstitute/leonardo

basePath: /

produces:
  - application/json

tags:
  - name: test
    description: Test API
  - name: cluster
    description: Clusters API

## UNCOMMENT THIS WHEN WE GET LEO CONF IN FIRECLOUD-DEVELOP
#security:
#  - googleoauth:
#      - openid
#      - email
#      - profile

#securityDefinitions:
#  googleoauth:
#    type: oauth2
#    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
#    flow: implicit
#    scopes:
#      openid: open id authorization
#      email: email authorization
#      profile: profile authorization

##########################################################################################
## PATHS
##########################################################################################
paths:

  '/api/ping':
    get:
      summary: Ping
      responses:
        200:
          description: Pong
        500:
          description: Internal Error
          schema:
            $ref: '#/definitions/ErrorReport'
      operationId: ping
      tags:
        - test
  '/api/cluster/{googleProject}/{clusterName}':
    put:
      summary: Creates a new dataproc cluster in the given project with the given name
      description: creates dataproc cluster with jupyters
      operationId: createCluster
      tags:
        - cluster
      parameters:
        - in: path
          name: googleProject
          description: googleProject
          required: true
          type: string
        - in: path
          name: clusterName
          description: clusterName
          required: true
          type: string
        - in: body
          description: Request for new cluster
          name: clusterRequest
          required: true
          schema:
            $ref: '#/definitions/ClusterRequest'
      responses:
        200:
          description: Cluster creation successful
          schema:
            $ref: '#/definitions/Cluster'
        500:
          description: Internal Error
          schema:
            $ref: '#/definitions/ErrorReport'

##########################################################################################
## DEFINITIONS
##########################################################################################
definitions:

  ErrorReport:
    description: ''
    required:
      - source
      - message
      - causes
      - stackTrace
    properties:
      source:
        type: string
        description: service causing error
      message:
        type: string
        description: what went wrong
      exceptionClass:
        type: string
        description: class of exception thrown
      statusCode:
        type: integer
        description: HTTP status code
      causes:
        type: array
        description: errors triggering this one
        items:
          $ref: '#/definitions/ErrorReport'
      stackTrace:
        type: array
        description: stack trace
        items:
          $ref: '#/definitions/StackTraceElement'

  StackTraceElement:
    description: ''
    required:
      - className
      - methodName
      - fileName
      - lineNumber
    properties:
      className:
        type: string
        description: class name
      methodName:
        type: string
        description: method name
      fileName:
        type: string
        description: source file name
      lineNumber:
        type: integer
        description: line number

  Cluster:
    description: ''
    required:
      - clusterName
      - googleId
      - googleProject
      - googleServiceAccount
      - googleBucket
      - operationName
      - status
      - createdDate
      - labels
    properties:
      clusterName:
        type: string
        description: The user-supplied name for the cluster
      googleId:
        type: string
        description: Google's UUID for the cluster
      googleProject:
        type: string
        description: The Google Project used to create the cluster
      googleServiceAccount:
        type: string
        description: The Google Service Account used to create the cluster
      googleBucket:
        type: string
        description: The Google Bucket associated with the cluster
      operationName:
        type: string
        description: Google's operation ID for the cluster
      status:
        type: string
        description: The current state of the cluster
      hostIp:
        type: string
        description: The IP address of the cluster master node
      createdDate:
        type: string
        description: The date and time the cluster was created, in ISO-8601 format
      destroyedDate:
        type: string
        description: The date and time the cluster was destroyed, in ISO-8601 format
      labels:
        type: object
        description: The labels to be placed on the cluster. Of type Map[String,String]

  ClusterRequest:
    description: ''
    required:
      - bucketPath
      - serviceAccount
      - labels
    properties:
      bucketPath:
        type: string
        description: The bucket where user's notebooks will be saved
      serviceAccount:
        type: string
        description: The service account of the user
      labels:
        type: object
        description: The labels to be placed on the cluster. Of type Map[String,String]
