jdk:
  - openjdk8

language: scala

scala:
  - 2.12.11

sudo: required

services:
  - docker

before_install:
  - docker rm -f mysql || true          # in case the after_success step does not run
  - docker pull mysql/mysql-server:5.6
  # port 3306 is not available because Travis runs its own MySQL after 2006-12-01
  - docker run -p 3307:3306 --name mysql -e MYSQL_ROOT_PASSWORD=leonardo-test -e MYSQL_USER=leonardo-test -e MYSQL_PASSWORD=leonardo-test -e MYSQL_DATABASE=leotestdb -d mysql/mysql-server:5.6

script:
  - SBT_OPTS=-J-Xmx3g sbt -Denv.type=test clean "test:compile" scalafmtCheckAll
  - SBT_OPTS=-J-Xmx3g sbt -Denv.type=test "project core" coverage test coverageReport
  - SBT_OPTS=-J-Xmx3g sbt -Denv.type=test -Dmysql.host=localhost -Dmysql.port=3307 "project http" coverage test coverageReport

after_success:
  - SBT_OPTS=-J-Xmx3g sbt "project http" coveralls
  - docker rm -f mysql

# https://www.scala-sbt.org/1.x/docs/Travis-CI-with-sbt.html describes how to enable caches for sbt dependencies
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt