codecov:
  require_ci_to_pass: true
  branch: develop

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
coverage:
  status:
    project:
      default:
        target: 70%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target

ignore: 
  - "automation"
  - "codegen_java"
  - "jenkins"
  - "pact4s"
  - "docker"
