codecov:
  require_ci_to_pass: yes
  branch: develop

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
coverage:
  status:
    project:
      default:
        target: 70%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
