FROM sbtscala/scala-sbt:openjdk-17.0.2_1.8.0_2.13.10

# This is only to make `sbt` work because `Version.scala` depends on `git` if this environment is not set
ENV GIT_HASH="0.0.1"

COPY automation/src /app/automation/src
COPY core/src /app/core/src
COPY project /app/project
COPY build.sbt /app
COPY automation-tests-docker-entrypoint.sh /app

WORKDIR /app

ENTRYPOINT ["bash", "automation-tests-docker-entrypoint.sh"]
