FROM hseeberger/scala-sbt:graalvm-ce-20.3.0-java11_1.4.5_2.13.4

# This is only to make `sbt` work because `Version.scala` depends on `git` if this environment is not set
ENV GIT_HASH="0.0.1"

COPY automation/src /app/automation/src
COPY core/src /app/core/src
COPY project /app/project
COPY build.sbt /app
COPY automation-tests-docker-entrypoint.sh /app

WORKDIR /app

ENTRYPOINT ["bash", "automation-tests-docker-entrypoint.sh"]
