FROM sbtscala/scala-sbt:openjdk-17.0.2_1.8.0_2.13.10

# This is only to make `sbt` work because `Version.scala` depends on `git` if this environment is not set
ENV GIT_HASH="0.0.1"

COPY automation/src /app/automation/src
COPY core/src /app/core/src
COPY project /app/project
COPY build.sbt /app
COPY automation-tests-docker-entrypoint.sh /app

RUN touch /app/key.json

# Downloading gcloud package
RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz

# Installing the package
RUN mkdir -p /usr/local/gcloud \
  && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
  && /usr/local/gcloud/google-cloud-sdk/install.sh

# Adding the package path to local
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

RUN mkdir -p /root/.ssh

WORKDIR /app

ENTRYPOINT ["bash", "automation-tests-docker-entrypoint.sh"]
