#cloud-config

write_files:
  - path: /etc/systemd/system/google-shutdown-scripts.service.d/override.conf
    permissions: 0644
    owner: root
    content: |
      [Unit]
      After=docker.service

runcmd:
  - systemctl daemon-reload