version: '2.4'
services:
  proxy:
    container_name: "${PROXY_SERVER_NAME}"
    image: "${PROXY_DOCKER_IMAGE}"
    ports:
      - "443:443"
    networks:
      - app_network
    volumes:
    - ${CERT_DIRECTORY}/jupyter-server.crt:/etc/ssl/certs/server.crt:ro
    - ${CERT_DIRECTORY}/jupyter-server.key:/etc/ssl/private/server.key:ro
    - ${CERT_DIRECTORY}/rootCA.pem:/etc/ssl/certs/ca-bundle.crt:ro
    - ${HOST_PROXY_SITE_CONF_FILE_PATH}:/etc/apache2/sites-enabled/site.conf
    restart: always
    environment:
      HTTPD_PORT: '80'
      SSL_HTTPD_PORT: '443'
      GOOGLE_PROJECT: "${GOOGLE_PROJECT}"
      RUNTIME_NAME: "${RUNTIME_NAME}"
      PROXY_SERVER_HOST_NAME: "${PROXY_SERVER_HOST_NAME}"