# Note: we need to stay on docker-compose version 2 because version 3 doesn't support
# configuring memory options in container mode. See discussion in:
# https://docs.docker.com/compose/compose-file/#resources
# https://github.com/docker/compose/issues/4513
version: '2'
services:
  rstudio:
    container_name: "${RSTUDIO_SERVER_NAME}"
    image: "${RSTUDIO_DOCKER_IMAGE}"
    network_mode: host
    restart: always
    environment:
      # needed to disable auth
      USER: "rstudio"
      GOOGLE_PROJECT: "${GOOGLE_PROJECT}"
      WORKSPACE_NAMESPACE: "${GOOGLE_PROJECT}"
      CLUSTER_NAME: "${CLUSTER_NAME}"
      RUNTIME_NAME: "${RUNTIME_NAME}"
      OWNER_EMAIL: "${OWNER_EMAIL}"
    volumes:
      - /work:/home/rstudio
      - /etc/rstudio-license-file.lic:/etc/rstudio-server/license.lic:ro
    env_file:
      - /etc/google_application_credentials.env
    # See https://docs.docker.com/engine/reference/run/#user-memory-constraints
    mem_limit: ${MEM_LIMIT}   # hard limit on memory consumption by the container
  
