# Note: we need to stay on docker-compose version 2 because version 3 doesn't support
# configuring memory options in container mode. See discussion in:
# https://docs.docker.com/compose/compose-file/#resources
# https://github.com/docker/compose/issues/4513
version: '2.4'
services:
  rstudio:
    container_name: "${RSTUDIO_SERVER_NAME}"
    image: "${RSTUDIO_DOCKER_IMAGE}"
    # Override the entrypoint from the Dockerfile so rserver starts with the below environment variables
    entrypoint: "tail -f /dev/null"
    restart: always
    network_mode: host
    environment:
      # needed to disable auth
      USER: "rstudio"
      GOOGLE_PROJECT: "${GOOGLE_PROJECT}"
      CLUSTER_NAME: "${RUNTIME_NAME}"
      RUNTIME_NAME: "${RUNTIME_NAME}"
      OWNER_EMAIL: "${OWNER_EMAIL}"
    volumes:
      - ${WORK_DIRECTORY}:/home/rstudio
      # workaround to specify the shm_size for docker shared memory: https://stackoverflow.com/questions/58952478/changing-shared-memory-size-in-docker-compose
      - type: tmpfs
          target: /dev/shm
          tmpfs:
            size: 1000000000 # ~1gb
    env_file:
      - /var/custom_env_vars.env
    # See https://docs.docker.com/engine/reference/run/#user-memory-constraints
    mem_limit: ${MEM_LIMIT}   # hard limit on memory consumption by the container
    memswap_limit: ${MEM_LIMIT}
