version: '2'
services:
  welder:
    container_name: "${WELDER_SERVER_NAME}"
    image: "${WELDER_DOCKER_IMAGE}"
    # Override entrypoint with a placeholder to keep the container running indefinitely.
    # The cluster init script will start welder via docker exec,
    # when Application Default Credentials are available.
    # See https://broadworkbench.atlassian.net/browse/IA-1026
    entrypoint: "tail -f /dev/null"
    network_mode: host
    restart: always
    environment:
      # TODO what env vars are actually needed here?
      GOOGLE_PROJECT: "${GOOGLE_PROJECT}"
      STAGING_BUCKET: "${STAGING_BUCKET}"
      CLUSTER_NAME: "${CLUSTER_NAME}"
      OWNER_EMAIL: "${OWNER_EMAIL}"
    volumes:
      # shared with jupyter
      - /work:/work
    env_file:
      - /etc/google_application_credentials.env

